/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6xrMay5lJtg
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import SearchInput from "@/components/search-input";
import BookList from "@/components/book/book-list";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { PlusIcon } from "@radix-ui/react-icons";

export default function Home() {
  return (
    <>
      <div className="container mx-auto py-8 px-4 md:px-6">
        <div className="flex items-center justify-start mb-6">
          {/* TODO: */}
          {/* <SearchInput /> */}
          <Button
            asChild
            variant="default"
            className="transition-transform duration-300 border shadow-md bg-primary rounded-sm font-semibold hover:-translate-y-2"
          >
            <Link href="/books/add">
              <PlusIcon className="w-5 h-5" />
              Add Book
            </Link>
          </Button>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
          <BookList />
        </div>
      </div>
    </>
  );
}
