/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6xrMay5lJtg
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import SearchInput from "@/components/search-input";
import BookList from "@/components/book/book-list";
import BookAdd from "@/components/book/book-add";
import { cx } from "class-variance-authority";
import { Dancing_Script } from "next/font/google";
import Auth from "@/components/auth";

const dancingScript = Dancing_Script({
  subsets: ["latin"], // 사용할 문자 셋
  weight: ["400", "700"], // 폰트 굵기
});

export default function Home() {
  return (
    <>
      <header className="w-full flex items-center justify-between px-4 md:px-6 py-4">
        <div className={cx(dancingScript.className, "text-3xl font-bold")}>
          Book Rating
        </div>
        <Auth />
      </header>
      <div className="container mx-auto py-8 px-4 md:px-6">
        <div className="flex items-center justify-between mb-6">
          <SearchInput />
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          <BookAdd />
          <BookList />
        </div>
      </div>
    </>
  );
}
